config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do 
    resources :comments
  end
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts	
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.post_id = @post.id
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

		def comment_params
			params.require(:comment).permit(:message)
		end

		def find_post
			@post = Post.find(params[:post_id])
		end

		def find_comment
			@comment = Comment.find(params[:id])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@posts = Post.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def new
		@post = current_user.posts.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def show
		
	end

	def create
		@post = @post = current_user.posts.build(post_params)
		@post.category_id = params[:category_id]

		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@post.category_id = params[:category_id]
		if @post.update(post_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end		
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

		def post_params
			params.require(:post).permit(:title, :body, :category_id)
		end

		def find_post
			@post = Post.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-warning">
  	<div class="panel-body">
  		<p><i><small><%= comment.message %></small></i></p>
		<%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_post_comment_path(comment.post, comment)%>
		<%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure ?"}%>	  
	</div>
</div>


app/views/comments/_form.html.erb
<div class="panel panel-info">
	<div class="panel-body">
	<%= simple_form_for([@post, @post.comments.build]) do |f|%>
		<%= f.input :message , as: :text, :input_html => { :rows => 3 , :style => 'width: 100%'}%>
		<%= link_to "Back", post_path(@post), {:class => 'btn btn-sm btn-warning'} %>
		<%= f.button :submit, {:class => 'btn btn-sm btn-primary pull-right'}%>	
	<% end %>
	</div>
</div>		

app/views/comments/edit.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<%= simple_form_for([@post, @comment]) do |f|%>
			<%= f.input :message , as: :text, :input_html => { :rows => 3 , :style => 'width: 100%'}%>
			<%= link_to "Back", post_path(@post), {:class => 'btn btn-sm btn-warning'} %>
			<%= f.button :submit, {:class => 'btn btn-sm btn-primary pull-right'} %>	
		<% end %>
	</div>
</div>		

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minipost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "miniPost", root_path, class: "navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All", posts_path, class: "link"%></li>
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, posts_path(category: category.name), class: "link"%></li>
              <% end %>
              </ul>
            </li>      
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
    	      	<li><%= link_to "New Post",new_post_path %></li>
    	        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>                
            <% else %>
    	        <li><%= link_to "Sign In", new_user_session_path %></li>                
    	        <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<%= simple_form_for @post do |f| %>
		  <%= f.input :title, label: 'Title'  %>
		  <%= select_tag(:category_id, options_for_select(@categories),:prompt => "Select Category",:class => 'form-control') %>  
		  <%= f.input :body , as: :text, :input_html => { :rows => 7 , :style => 'width: 100%'}%>
		  <%= link_to "Back", posts_path, {:class => 'btn btn-sm btn-warning'} %>
		  <%= f.button :submit, {:class => 'btn btn-sm btn-primary pull-right'} %>
		<% end %>
	</div>
</div>		

app/views/posts/edit.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<%= simple_form_for @post do |f| %>
		  <%= f.input :title, label: 'Title'  %>
		  <%= f.select :category_id, @categories,{}, {:class => 'form-control'} %>
		  <%= f.input :body, as: :text, :input_html => { :rows => 7 , :style => 'width: 100%'} %>
		  <%= link_to "Back", post_path(@post), {:class => 'btn btn-sm btn-warning'} %>
		  <%= f.button :submit, {:class => 'btn btn-sm btn-primary pull-right'} %>
		<% end %>	
	</div>
</div>

app/views/posts/index.html.erb
<% if @posts.count == 0%>
	<h5>No post available in this category</h5>
<% else %>
	<% @posts.each do |post| %>
		<div class="panel panel-info">
		  <div class="panel-heading">
		  <h3 class="panel-title"><%= link_to post.title, post_path(post) %>
		  	<span class="label label-primary pull-right"><%= post.category.name %></span>
		  </h3>
		  </div>
		  <div class="panel-body">
		    <%= truncate(post.body, length: 250) %>
		  </div>
		</div>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%=  @post.title %></h3>
  </div>
  <div class="panel-body">
    <%=  @post.body %>
  </div>
  <div class="panel-footer">

	<%= link_to "Back", root_path, :class => 'btn btn-warning btn-sm' %>
	<% if user_signed_in? %>
		<!-- Single button -->
		<div class="btn-group pull-right">
		 	<button type="button" class="btn btn-info btn-sm">Action</button>
		  	<button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    	<span class="caret"></span>
		    	<span class="sr-only">Toggle Dropdown</span>
		  	</button>
			 <ul class="dropdown-menu">
			  	<% if @post.user_id == current_user.id %>	
				    <li><%= link_to 'Edit'.html_safe, edit_post_path(@post) %></li>
				    <li><%= link_to 'Delete'.html_safe, post_path(@post),method: :delete, data: { confirm: "Are you sure ? "} %></li>
			    	<li role="separator" class="divider"></li>
			    <% end %>
			    <li><%= link_to "Comment", new_post_comment_path(@post) %></li>
			</ul>
		</div>
	<% end %>  	  	
	</div> 
</div>
<% if user_signed_in? %>
	<% if @post.user_id == current_user.id %>	
		<%= render @post.comments %>
	<% end %>
<% end %>



